---
- name: Create aws nginx instance
  hosts: localhost
  vars:
    region: "us-east-2"
    security_group_name: "SG_NGINX"
    vpc_name: "VPC_NGINX"
    subnet_name: "SUBNET_NGINX"
    acl_name: "ACL_NGINX"
  tasks:
  - name: Ensure boto and boto3 modules are installed
    pip:
      name: "{{ item }}"
    with_items:
      - boto3
      - botocore

  - name: Terminate all aws nginx instance(s)
    ec2_instance:
      state: absent
      filters:
        "tag:role": NGINX 
    ignore_errors: yes

  - name: Create a new ec2 key pair, returns generated private key
    ec2_key:
      name: my_keypair
    register: key_result

  - name: Save key pair 
    copy: 
      content: "{{ key_result.key.private_key }}"
      dest: "/root/.ssh/my_keypair.pem" 
      mode: 0400
    when: key_result.changed

  - name: create VPC
    ec2_vpc_net:
       name: "{{ vpc_name }}"
       cidr_block: "10.10.0.0/24"
       region: "{{ region }}"
       state: present
    register: result_vpc

  - name: associate subnet to the VPC
    ec2_vpc_subnet:
     state: present
     vpc_id: "{{ result_vpc.vpc.id }}"
     region: "{{ region }}"
     cidr: "10.10.0.0/26"
     map_public: yes
     resource_tags:
       Name: "{{ subnet_name }}"
    register: result_subnet

  - name: Create security group
    ec2_group:
      name: '{{security_group_name}}'
      description: sg with rule descriptions
      region: '{{region}}'
      vpc_id: "{{ result_vpc.vpc.id }}"
      state: present
      rules:
        - proto: tcp
          ports:
            - 80
          cidr_ip: 0.0.0.0/0
          rule_desc: allow all on port 80
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
    register: result_sg

  - name: create ec2 VPC Network access control list
    ec2_vpc_nacl:
      vpc_id: "{{ result_vpc.vpc.id }}"
      region: "{{ region }}"
      state: present
      name: "{{ acl_name }}"
      subnets: [ "{{ result_subnet.subnet.id }}" ]
      tags:
        Name: "{{ acl_name }}"
        Description: "{{ acl_name }}"
      # ingress acl rules
      ingress:
        # rule no, protocol, allow/deny, cidr, icmp_type, icmp_code, port from, port to
        # allow ingress port 22
        - [100, 'tcp', 'allow', "0.0.0.0/0", null, null, 22, 22]
        # allow ingress port 80
        - [200, 'tcp', 'allow', "0.0.0.0/0", null, null, 80, 80]
      # egress acl rules
        # rule no, protocol, allow/deny, cidr, icmp_type, icmp_code, port from, port to
      egress:
            - [100, 'all', 'allow', '0.0.0.0/0', null, null, null, null]
    register: result_acl

  - name: create IGW
    ec2_vpc_igw:
      vpc_id: "{{ result_vpc.vpc.id }}"
      region: "{{ region }}"
      state: "present"
    register: result_igw

  - name: Route IGW
    ec2_vpc_route_table:
    vpc_id: "{{ result_vpc.vpc.id }}"
    region: "{{ region }}"
    subnets:
      - "{{ result_subnet.subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ result_igw.gateway_id }}"

  - name: Create instances
    ec2:
      key_name: my_keypair
      group: '{{security_group_name}}'
      region: '{{region}}'
      assign_public_ip: true
      volumes:
        - device_name: /dev/sdh
          volume_type: gp2
          volume_size: 15
          delete_on_termination: true
      instance_type: t2.micro
      image: ami-013de1b045799b282
      vpc_subnet_id: "{{ result_subnet.subnet.id }}"
      wait: yes
      wait_timeout: 500
      count: 3
      instance_tags:
        role: "NGINX"
    register: result_instance

  - debug:
     var: result_instance

#   - ec2_instance_info:
#       filters:
#         "tag:role": NGINX 
#     register: result_instance_info

#   - debug:
#       var: result_instance_info

  - set_fact:
      instance_ips: "{{ result_instance | json_query('instances[*].public_ip') }}"
    
  - debug:
      var: instance_ips

  - name: Add host to group 'ec2_nginx'
    add_host:
       name: '{{ item }}'
       groups: ec2_nginx
    with_items: '{{instance_ips}}'

#   - name: Wait for SSH to come up
#     delegate_to: "{{ item.public_dns_name }}"
#     wait_for_connection:
#       delay: 20
#       timeout: 320
#     loop: "{{ result_instance.instances }}"

- name: deploy nginx
  hosts: ec2_nginx
  tasks:
    - name: Ensure nginx is installed
      apt:
        name: nginx
        state: present
    - name: Copy hello page
      copy:
        src: index.nginx-debian.html
        dest: /var/www/html/index.nginx-debian.html
        follow: yes
      notify:
        - restart nginx

- handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted