---
- name: Create aws nginx instance
  hosts: localhost
  vars:
    region: "us-east-2"
    security_group_name: "SG_NGINX"
    vpc_name: "VPC_NGINX"
    subnet_name: "SUBNET_NGINX"
  tasks:
  - name: Ensure boto and boto3 modules are installed
    pip:
      name: "{{ item }}"
    with_items:
      - boto3
      - botocore

  - ec2_instance:
      state: absent
      filters:
        "tag:role": NGINX 
    ignore_errors: yes

  - name: Create a new ec2 key pair, returns generated private key
    ec2_key:
      name: my_keypair
    register: key_result

  - name: Save key pair 
    copy: 
      content: "{{ key_result.key.private_key }}"
      dest: "/root/.ssh/my_keypair.pem" 
      mode: 0400
    when: key_result.changed

  - name: Create security group
    ec2_group:
      name: '{{security_group_name}}'
      description: sg with rule descriptions
      region: '{{region}}'
      state: present
      rules:
        - proto: tcp
          ports:
            - 80
          cidr_ip: 0.0.0.0/0
          rule_desc: allow all on port 80
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 
            - 130.193.0.0/16
            - 84.201.0.0/16
    register: result_sg

  - debug:
     var: result_sg

  - name: create VPC
    ec2_vpc_net:
       name: "{{ vpc_name }}"
       cidr_block: "10.10.0.0/24"
       region: "{{ region }}"
       state: present
    register: result_vpc

  - name: associate subnet to the VPC
    ec2_vpc_subnet:
     state: present
     vpc_id: "{{ result_vpc.vpc.id }}"
     region: "{{ region }}"
     cidr: "10.0.1.16/28"
     map_public: yes
     resource_tags:
       Name: "{{ subnet_name }}"
    register: result_subnet

  - name: create instances
    ec2:
      key_name: my_keypair
      group: '{{security_group_name}}'
      region: '{{region}}'
      assign_public_ip: true
      volumes:
      - device_name: /dev/sdh
        ebs:
          volume_size: 15
          delete_on_termination: true
      instance_type: t2.micro
      image: ami-013de1b045799b282
      vpc_subnet_id: "{{ subnet_result.subnet.id }}"
      wait: yes
      wait_timeout: 500
      count: 3
      instance_tags:
        role: "NGINX"
    register: result_instance

  - debug:
     var: result_instance

#   - ec2_instance_info:
#       filters:
#         "tag:role": NGINX 
#     register: result_instance_info

#   - debug:
#       var: result_instance_info

  - set_fact:
      instance_ips: "{{ result_instance | json_query('instances[*].public_ip') }}"
    
  - debug:
      var: instance_ips

  - name: Add host to group 'ec2_nginx'
    add_host:
       name: '{{ item.public_ip }}'
       groups: ec2_nginx
    loop: '{{result_instance.instances}}'

  - name: Wait for SSH to come up
    wait_for:
      host: '{{ item.public_ip }}'
      port: 22
      delay: 10
      timeout: 320
    loop: "{{ result_instance.instances }}"

- name: deploy nginx
  hosts: ec2_nginx
  tasks:
    - name: Ensure nginx is installed
      apt:
        name: nginx
        state: present
    - name: Copy hello page
      copy:
        src: index.nginx-debian.html
        dest: /var/www/html/index.nginx-debian.html
        follow: yes
      notify:
        - restart nginx

- handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted